<a href="https://colab.research.google.com/github/mohak0900/Summer-Analytics-2023/blob/main/capstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
from sklearn.preprocessing import LabelEncoder
%matplotlib inline

In [ ]:
traindata= pd.read_csv('/content/Train_Data.csv')
testdata= pd.read_csv('/content/Test_Data.csv')

In [ ]:
# getting row and column info about the data
shape=traindata.shape
print('\nDataFrame Shape :', shape)
print('\nNumber of rows :', shape[0])
print('\nNumber of columns :', shape[1])
traindata.head()


DataFrame Shape : (22584, 19)

Number of rows : 22584

Number of columns : 19


pc      ld    m0    m1    m2       m3        m4       m5        m6       m7  \
0  y   83.71  63.0   7.2  52.5  14.0232  130.8300  12.4280  188.8425   8.9520   
1  y  108.94  31.5  12.8  84.0  13.2840  128.8350  13.5256  183.0990   8.8520   
2  E  169.65   0.0   5.6  73.5  14.5472  128.9295  13.6424  174.4680   8.9800   
3  x  122.42  31.5   7.2  63.0  15.0152  119.8575  12.3344  186.8580  10.7208   
4  E  125.43  94.5   7.2  42.0  14.4176  135.4290  14.5824  187.8135   9.3088   

         m8       m9       m10      m11       m12      m13       m14   ma  \
0  201.1905   9.2896  141.9075  16.0968  150.3390  12.4880  173.1240  m78   
1  207.2385   8.4704  154.7805  13.3304  101.0205  12.5096  131.4075  m78   
2  190.3125  11.3056  156.7650      NaN  122.5350  11.7136  176.8200  m76   
3  193.8195  10.6096  175.7490      NaN  124.8030  13.8424  168.2625  m55   
4  203.1540   9.8280  172.7040  14.4720  120.2145      NaN  150.1185  m76   

   pred  
0     0  
1     0  
2     1  
3     0  
4     0

In [ ]:
# statistical measures about the data
traindata.describe()

ld            m0            m1            m2            m3  \
count  22362.000000  22584.000000  22584.000000  22584.000000  22270.000000   
mean     127.893905     78.002391      6.589621     65.664054     14.241585   
std       39.078070     43.156539      3.360565     34.690224      0.801207   
min       33.160000      0.000000      0.000000      0.000000     11.174400   
25%      100.090000     42.000000      4.000000     42.000000     13.703200   
50%      122.355000     73.500000      6.400000     63.000000     14.239200   
75%      149.247500    105.000000      8.800000     84.000000     14.786400   
max      385.860000    283.500000     23.200000    252.000000     17.199200   

                 m4            m5            m6            m7            m8  \
count  22117.000000  22008.000000  21909.000000  21796.000000  21684.000000   
mean     123.207337     13.697683    183.894313      9.380175    199.786867   
std       10.481427      0.798463     10.478648      0.800904     10.578785   
min       84.084000     10.250400    133.507500      6.374400    159.778500   
25%      116.067000     13.147200    176.809500      8.842200    192.651375   
50%      123.207000     13.702400    183.949500      9.378800    199.741500   
75%      130.357500     14.239200    190.932000      9.916000    206.944500   
max      173.082000     17.140000    226.201500     12.335200    249.973500   

                 m9           m10           m11           m12           m13  \
count  21537.000000  21484.000000  21357.000000  21203.000000  21085.000000   
mean       9.143454    169.239563     15.334764    122.868388     12.521853   
std        0.799078     14.754047      1.214489     15.669803      0.923849   
min        6.029600    100.170000     10.096000     54.253500      8.712000   
25%        8.604000    159.715500     14.529600    112.365750     11.912000   
50%        9.143200    169.359750     15.364000    123.007500     12.504000   
75%        9.679200    178.741500     16.161600    133.465500     13.098400   
max       12.329600    236.029500     20.512000    185.461500     18.170400   

                m14          pred  
count  20995.000000  22584.000000  
mean     168.530817      0.215772  
std       15.643776      0.411366  
min       95.970000      0.000000  
25%      158.109000      0.000000  
50%      168.441000      0.000000  
75%      179.361000      0.000000  
max      234.181500      1.000000

In [ ]:
testdata.describe()

index           ld           m0           m1           m2  \
count  3986.000000  3958.000000  3986.000000  3986.000000  3986.000000   
mean   1992.500000   127.443896    77.098344     6.565580    65.863397   
std    1150.803415    38.760121    43.609973     3.353944    35.061915   
min       0.000000    41.110000     0.000000     0.000000     0.000000   
25%     996.250000    99.207500    42.000000     4.000000    42.000000   
50%    1992.500000   122.565000    73.500000     6.400000    63.000000   
75%    2988.750000   148.335000   105.000000     8.800000    84.000000   
max    3985.000000   346.970000   304.500000    20.800000   220.500000   

                m3           m4           m5           m6           m7  \
count  3919.000000  3915.000000  3886.000000  3865.000000  3837.000000   
mean     14.185697   123.064616    13.728068   183.685280     9.334244   
std       0.797992    10.331141     0.789151    10.338274     0.798309   
min      11.444800    86.058000     9.658400   148.480500     6.520000   
25%      13.646800   115.956750    13.189000   176.778000     8.806400   
50%      14.172800   123.144000    13.719200   183.781500     9.320000   
75%      14.708800   129.984750    14.268600   190.501500     9.880800   
max      16.998400   159.862500    16.300000   217.581000    12.215200   

                m8           m9          m10          m11          m12  \
count  3838.000000  3806.000000  3786.000000  3745.000000  3766.000000   
mean    199.604852     9.150947   169.215523    15.354230   122.918038   
std      10.654589     0.800692    14.814110     1.228788    15.424807   
min     160.314000     6.160800    97.891500     9.968800    68.701500   
25%     192.234000     8.619200   159.581625    14.567200   112.457625   
50%     199.578750     9.152400   169.176000    15.383200   123.180750   
75%     206.889375     9.688600   178.972500    16.184800   133.431375   
max     235.956000    11.919200   228.049500    19.769600   182.616000   

               m13          m14  
count  3711.000000  3701.000000  
mean     12.524991   168.382988  
std       0.926298    15.787681  
min       8.841600   109.788000  
25%      11.912400   157.972500  
50%      12.492000   168.231000  
75%      13.100800   179.361000  
max      16.501600   229.393500

In [ ]:
# checking missing values
traindata.isnull().sum()

pc         0
ld       222
m0         0
m1         0
m2         0
m3       314
m4       467
m5       576
m6       675
m7       788
m8       900
m9      1047
m10     1100
m11     1227
m12     1381
m13     1499
m14     1589
ma         0
pred       0
dtype: int64

In [ ]:
#removing null values
traindata.dropna()

pc      ld     m0    m1     m2       m3        m4       m5        m6  \
0      y   83.71   63.0   7.2   52.5  14.0232  130.8300  12.4280  188.8425   
1      y  108.94   31.5  12.8   84.0  13.2840  128.8350  13.5256  183.0990   
5      y  160.61   84.0  10.4   73.5  13.4656  121.3485  14.2832  188.7480   
7      z  136.55   73.5   9.6   94.5  14.1792  121.4430  13.8368  189.3465   
8      z  101.09   94.5   8.8  252.0  13.5632  109.3785  13.5984  185.8710   
...   ..     ...    ...   ...    ...      ...       ...      ...       ...   
22578  y  126.41   52.5   8.0   63.0  15.2552  133.0875  15.0120  191.3625   
22579  E  139.08   73.5   7.2   84.0  13.8016  115.9725  13.8856  189.0000   
22581  w  115.63  147.0   4.8   31.5  13.4344  115.5000  13.5752  190.8900   
22582  y  216.26  105.0   4.8   31.5  13.8176  112.5285  13.2408  166.8555   
22583  E  120.65   31.5   6.4   42.0  14.8536  149.5305  13.1448  189.3570   

            m7        m8      m9       m10      m11       m12      m13  \
0       8.9520  201.1905  9.2896  141.9075  16.0968  150.3390  12.4880   
1       8.8520  207.2385  8.4704  154.7805  13.3304  101.0205  12.5096   
5      10.6888  195.7095  9.8808  167.1810  15.5344  103.9920  13.8584   
7       8.8304  211.2705  9.3368  165.4485  15.8424  124.3725  12.5552   
8       8.8368  188.7165  8.5168  163.4010  15.9320  113.0115  13.4072   
...        ...       ...     ...       ...      ...       ...      ...   
22578   9.8312  206.9340  9.4808  167.4960  14.1520   88.3575  12.1736   
22579   8.6536  196.7490  9.2216  170.8770  17.3744  164.7240  12.5720   
22581   9.6144  219.6810  9.3120  156.7440  15.9712  109.3680  12.8480   
22582   9.0160  200.3610  7.4760  174.7830  16.7888  135.1770  12.7336   
22583  10.0600  192.2970  9.0448  190.2495  16.4432  107.6355  12.7224   

            m14   ma  pred  
0      173.1240  m78     0  
1      131.4075  m78     0  
5      169.7850  m78     0  
7      158.0775  m75     0  
8      150.6120  m75     1  
...         ...  ...   ...  
22578  189.5670  m78     0  
22579  144.4065  m76     1  
22581  153.5835  m78     0  
22582  158.0985  m78     0  
22583  169.7010  m76     0  

[13298 rows x 19 columns]

In [ ]:
#Declare feature vector and target variable
X = traindata.drop(['pred'], axis=1)
y = traindata['pred']

In [ ]:
#Splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [ ]:
# check the shape of X_train and X_test
# check the shape of X_train and X_test
print(X_train.shape)
print(X_test.shape)

(15131, 18)
(7453, 18)


In [ ]:
X_train = X_train.apply(LabelEncoder().fit_transform)
X_test = X_test.apply(LabelEncoder().fit_transform)

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier, XGBRFClassifier
from xgboost import plot_tree, plot_importance
from sklearn.ensemble import AdaBoostClassifier

from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, roc_curve
from sklearn import preprocessing
from sklearn.feature_selection import RFE

In [ ]:
def score(model, title = "Default"):
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    print(confusion_matrix(y_test, preds))
    accuracy = round(accuracy_score(y_test, preds), 5)
    print('Accuracy for', title, ':', accuracy, '\n')

In [ ]:
lg = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial')
score(lg, "Logistic Regression")

[[5878    0]
 [1575    0]]
Accuracy for Logistic Regression : 0.78868 



In [ ]:
# AdaBoostClassifier
ada_boost = AdaBoostClassifier(n_estimators=1000, random_state=0)
score(ada_boost, "AdaBoost Classifier")

[[5835   43]
 [1567    8]]
Accuracy for AdaBoost Classifier : 0.78398 



In [ ]:
# Random Forest
rf = RandomForestClassifier(n_estimators=1000, max_depth=10, random_state=0)
score(rf, "Random Forest Classifier")

[[5878    0]
 [1575    0]]
Accuracy for Random Forest Classifier : 0.78868 



In [ ]:
# Naive Bayes: GaussianNB
#YOUR CODE HERE

from sklearn.model_selection import GridSearchCV
nb_param = {'var_smoothing':[0.001,0.01,0.1,1]}
nb = GaussianNB()
nb_cv = GridSearchCV(nb, param_grid=nb_param, cv=10)
score(nb_cv, "Naive Bayes")


[[5878    0]
 [1575    0]]
Accuracy for Naive Bayes : 0.78868 



In [ ]:
# KNN: KNeighborsClassifier
#YOUR CODE HERE

knn=  KNeighborsClassifier(n_neighbors=1)
score(knn, "K Nearest Neighbour")

[[4788 1090]
 [1247  328]]
Accuracy for K Nearest Neighbour : 0.68643 



In [ ]:
# Decission trees: DecisionTreeClassifier
#YOUR CODE HERE

dtree = DecisionTreeClassifier()
score(dtree, "Decision Tree Classifier")

[[4770 1108]
 [1294  281]]
Accuracy for Decision Tree Classifier : 0.67771 



In [ ]:
# XGBClassifier
#YOUR CODE HERE
le = LabelEncoder()
y_train_1 = le.fit_transform(y_train)
xgb = XGBClassifier(n_estimators = 1000, learning_rate = 0.01, max_depth = 3)
xgb.fit(X_train.values, y_train_1)
pred_1 = xgb.predict(X_test)
pred_decoded_1 = le.inverse_transform(pred_1)
print(confusion_matrix(y_test, pred_decoded_1))
accuracy = round(accuracy_score(y_test, pred_decoded_1), 5)
print('Accuracy for XGB Classifier:', accuracy, '\n')


[[5878    0]
 [1575    0]]
Accuracy for XGB Classifier: 0.78868 

